-- =============================================================================
-- Seed baseline RBAC data: default roles and permissions.
-- Idempotent-friendly (fixed names, unique-constrained). UUIDs generated by the DB
-- (gen_random_uuid() is built into PostgreSQL 13+). version starts at 0.
-- =============================================================================

INSERT INTO roles (id, version, created_at, updated_at, created_by, name, description) VALUES
    (gen_random_uuid(), 0, now(), now(), 'system', 'ROLE_USER',  'Standard authenticated user'),
    (gen_random_uuid(), 0, now(), now(), 'system', 'ROLE_ADMIN', 'Platform administrator');

INSERT INTO permissions (id, version, created_at, updated_at, created_by, name, description) VALUES
    (gen_random_uuid(), 0, now(), now(), 'system', 'user:read',       'Read user accounts'),
    (gen_random_uuid(), 0, now(), now(), 'system', 'user:write',      'Create/modify user accounts'),
    (gen_random_uuid(), 0, now(), now(), 'system', 'role:read',       'Read roles and permissions'),
    (gen_random_uuid(), 0, now(), now(), 'system', 'role:write',      'Manage roles and permissions'),
    (gen_random_uuid(), 0, now(), now(), 'system', 'profile:read',    'Read own profile'),
    (gen_random_uuid(), 0, now(), now(), 'system', 'profile:write',   'Modify own profile');

-- ROLE_ADMIN → every permission.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ROLE_ADMIN';

-- ROLE_USER → self-scoped profile permissions only.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r JOIN permissions p ON p.name IN ('profile:read', 'profile:write')
WHERE r.name = 'ROLE_USER';
